version: '1.0'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: backend
    environment:
      NODE_ENV: production
    ports:
      - "5040:3000" 
    volumes:
      - .:/usr/src/app
    command: ["node", "dist/main.js"]
