version: '3.3'

services:
  netman_backend_image:
    build:
      context: .
      dockerfile: dockerfile
      target: production
    container_name: netman_backend
    image: johedotcom/netman-backend-repository:latest
    environment:
      NODE_ENV: production
    ports:
      - "5040:3000" 
    volumes:
      - .:/usr/src/app
    command: ["node", "dist/main.js"]
