version: '3.3'

services:
  netman_backend_image:
    build:
      context: .
      dockerfile: dockerfile
      target: production
    container_name: netman_backend
    image: johedotcom/netman-backend-repository:latest
    restart: always
    ports:
      - '0.0.0.0:4040:3000'
    volumes:
      - .:/usr/src/app
    command: ['node', 'dist/src/main.js']