version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
      target: production
    container_name: backend
    image: backend_image
    environment:
      NODE_ENV: production
    ports:
      - "5040:3000" 
    volumes:
      - .:/usr/src/app
    command: ["node", "dist/main.js"]
